name: "Despliegue de sitio web en Github Pages"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargando código del repositorio 🛎️
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Instalando dependencias 🔧
        run: npm install


      - name: Creando la versión a publicar 🏗️
        run: npm run build
        env:
          NODE_ENV: production

      - name: Publicando en GH Pages 🚀
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs